version: "3.4"

services:
  app:
    image: cornellappdev/scoop-prod
    hostname: app
    env_file: .envrc
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python src/manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000